pool: Default 
 
trigger:
  - efficient-webjars
  
resources: 
  repositories: 
    - repository: 'myrepo'
      endpoint: 'github.com_purna970' 
      ref: 'refs/heads/main'
      name: 'purna970/javatemplate'
      type: 'github'

stages:
  - stage: buildandpublish
    displayName: BuildAndPublish 
    jobs:
      - job: buildjob 
        steps:
          - template: java/spc.yaml@myrepo 
            parameters: 
              javaversionoption: '1.17' 
              java: "java-1.17.0-openjdk-amd64" 
              maven: "Maven@3" 
              goals: "package" 
              pathtopublish: "target/spring-petclinic-2.7.3.jar"
              artifactname: "mavenartifact"
              publishlocation: "container" 

  - stage: downloadpipelineartifact
    displayName: DownloadPipelineArtifacts 
    dependsOn: buildandpublish         
    jobs: 
      - job: downloadartifact
        steps: 
          - task: DownloadPipelineArtifact@2 
            inputs:
              buildType: "current" 
              artifactname: "mavenartifact"
              targetPath: "/tmp/"  
          - script: ansible-playbook -i hosts spc_playbook.yaml
